Traceback (most recent call last):
  File "/Users/marcoo_sg/Desktop/sem/CSELEC1C/ShopZada_ETL/data_pipeline/data_pipeline_enterprise_department/data_pipeline_enterprise_department_order_with_merchant_01_uppercase_columns/data_pipeline_enterprise_department_order_with_merchant_01_uppercase_columns.py", line 20, in <module>
    df_data1 = pd.read_parquet(os.path.join('..', '..', 'data', 'enterprise_department', 'order_with_merchant_data1.parquet'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py", line 265, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py", line 139, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pandas/io/common.py", line 872, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../data/enterprise_department/order_with_merchant_data1.parquet'
